---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2023 The Nephio Authors.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

- name: Init job ids array
  ansible.builtin.set_fact:
    all_kpt_apply: []

- name: Deploy Nephio packages
  ansible.builtin.include_role:
    name: kpt
  loop: "{{ nephio.kpt.packages }}"
  vars:
    repo_uri: "{{ item.repo_uri }}"
    pkg: "{{ item.pkg }}"
    version: "{{ item.version }}"
    context: "{{ k8s.context }}"
    kpt_async: "{{ item.async }}"
    kpt_poll: "{{ item.poll }}"

- name: Wait for packages to be applied
  ansible.builtin.async_status:
    jid: "{{ item.ansible_job_id }}"
  register: job_result
  loop: "{{ all_kpt_apply }}"
  when: all_kpt_apply is defined
  until: job_result.finished
  retries: 60
  delay: 5

- name: Add HTTP proxy environment variables to key pods
  when: lookup('ansible.builtin.env', 'http_proxy') or lookup('ansible.builtin.env', 'https_proxy') or lookup('ansible.builtin.env', 'HTTP_PROXY') or lookup('ansible.builtin.env', 'HTTPS_PROXY')
  block:
    - name: Get Kubernetes API IP
      ansible.builtin.command: kubectl get svc kubernetes -n default -o jsonpath={.spec.clusterIP}
      register: k8s_api_ip

    - name: Calculate no_proxy
      ansible.builtin.set_fact:
        no_proxy: "{{ lookup('ansible.builtin.env', 'no_proxy', default=lookup('ansible.builtin.env', 'NO_PROXY', default='127.0.0.1,localhost,.cluster,.local,.svc,.novalocal,.nsn-net.net,.nsn-rdnet.net,.nokia.net,.xip.io,169.254.169.254' ) )  }},{{k8s_api_ip.stdout}}"

    - name: Update porch-server
      ansible.builtin.shell: |
        kubectl set env -n porch-system deployment/porch-server \
        http_proxy={{ lookup('ansible.builtin.env', 'http_proxy') }} \
        https_proxy={{ lookup('ansible.builtin.env', 'https_proxy') }} \
        HTTP_PROXY={{ lookup('ansible.builtin.env', 'HTTP_PROXY') }} \
        HTTPS_PROXY={{ lookup('ansible.builtin.env', 'HTTPS_PROXY') }} \
        no_proxy="{{ no_proxy }}" \
        NO_PROXY="{{ no_proxy }}"


- name: Wait for deployments
  ansible.builtin.include_tasks: wait_deployments.yml
  loop: "{{ nephio.k8s.namespaces }}"
  loop_control:
    loop_var: namespace
  vars:
    context: "{{ k8s.context }}"

- name: Create gitea user password in nephio-system namespace
  kubernetes.core.k8s:
    context: "{{ k8s.context }}"
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: git-user-secret
        namespace: nephio-system
      type: kubernetes.io/basic-auth
      stringData:
        username: "{{ gitea.k8s.username }}"
        password: "{{ gitea.k8s.password }}"
  no_log: true

- name: Deploy Nephio webui
  ansible.builtin.include_role:
    name: kpt
  vars:
    repo_uri: "{{ nephio_webui.kpt.package.repo_uri }}"
    pkg: "{{ nephio_webui.kpt.package.pkg }}"
    version: "{{ nephio_webui.kpt.package.version }}"
    context: "{{ k8s.context }}"
    kpt_async: 600
    kpt_poll: 5

- name: Wait for Nephio webui deployment
  ansible.builtin.include_tasks: wait_deployments.yml
  vars:
    context: "{{ k8s.context }}"
    namespace: "{{ nephio_webui.k8s.namespace }}"
